/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianCheckboxSort
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var DEFAULT_SETTINGS = {
  enableGlobalCheckboxSort: true,
  // Default to enabled
  debugMode: false
  // Default disabled
};
function checkboxClickHandlerExtension(onClick) {
  return import_view.ViewPlugin.define((view) => {
    const handleClick = (event) => {
      const target = event.target;
      if (target instanceof HTMLInputElement && target.type === "checkbox" && target.classList.contains("task-list-item-checkbox")) {
        const pos = view.posAtCoords({
          x: event.clientX,
          y: event.clientY
        });
        if (pos !== null) {
          const line = view.state.doc.lineAt(pos);
          const lineNumber = line.number - 1;
          try {
            onClick(lineNumber);
          } catch (e) {
            console.error("Error executing onClick callback:", e);
          }
        }
      }
    };
    view.dom.addEventListener("click", handleClick);
    return {
      destroy() {
        view.dom.removeEventListener("click", handleClick);
      }
    };
  });
}
var ObsidianCheckboxSort = class extends import_obsidian.Plugin {
  debugLog(message, ...optionalParams) {
    if (this.settings.debugMode) {
      console.debug(message, ...optionalParams);
    }
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new CheckboxSortSettingTab(this.app, this));
    const extension = checkboxClickHandlerExtension((lineNumber) => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view && view.file) {
        this.sortCheckboxesAroundClick(view, lineNumber);
      } else {
        console.error(
          "CALLBACK: Could not get MarkdownView to process checkbox click."
        );
      }
    });
    try {
      this.registerEditorExtension(extension);
      this.debugLog(
        "Checkbox Sort editor extension registered successfully."
      );
    } catch (e) {
      console.error(
        "Failed to register Checkbox Sort editor extension:",
        e
      );
    }
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // --- sortCheckboxesAroundClick ---
  async sortCheckboxesAroundClick(view, clickedLineNumber) {
    const editor = view.editor;
    const file = view.file;
    let fileLevelSortingEnabled = this.settings.enableGlobalCheckboxSort;
    let settingSource = "Global Default";
    if (file) {
      const fileCache = this.app.metadataCache.getFileCache(file);
      const frontmatter = fileCache == null ? void 0 : fileCache.frontmatter;
      if (frontmatter && frontmatter["checkbox-sort"] !== void 0 && typeof frontmatter["checkbox-sort"] === "boolean") {
        fileLevelSortingEnabled = frontmatter["checkbox-sort"];
        settingSource = "File Frontmatter";
      }
    }
    this.debugLog(
      `Starting effective setting based on Global/Frontmatter: ${fileLevelSortingEnabled} (Source: ${settingSource})`
    );
    const totalLines = editor.lineCount();
    let effectiveSortingEnabled = fileLevelSortingEnabled;
    const clickedLineText = editor.getLine(clickedLineNumber);
    const currentIndent = this.getIndentationLevel(clickedLineText);
    const listItemRegex = /^\s*[-*+]\s+/;
    let blockStartLine = clickedLineNumber;
    for (let i = clickedLineNumber - 1; i >= 0; i--) {
      const line = editor.getLine(i);
      const indent = this.getIndentationLevel(line);
      if (!listItemRegex.test(line)) break;
      if (indent === currentIndent) {
        blockStartLine = i;
      } else if (indent < currentIndent) {
        break;
      }
    }
    this.debugLog(
      `Peer block starts at line: ${blockStartLine}. Scanning for list marker...`
    );
    const enableMarker = "%%checkbox-sort: true%%";
    const disableMarker = "%%checkbox-sort: false%%";
    let listMarkerFound = null;
    let foundMarkerLine = -1;
    this.debugLog(
      `Scanning upwards from line ${clickedLineNumber - 1} for list marker...`
    );
    for (let scanLineNum = clickedLineNumber - 1; scanLineNum >= 0; scanLineNum--) {
      const lineContent = editor.getLine(scanLineNum).trim();
      if (lineContent.includes(enableMarker)) {
        listMarkerFound = true;
        settingSource = "List Marker (Enable)";
        foundMarkerLine = scanLineNum;
        this.debugLog(`Found enable marker at line ${scanLineNum}`);
        break;
      }
      if (lineContent.includes(disableMarker)) {
        listMarkerFound = false;
        settingSource = "List Marker (Disable)";
        foundMarkerLine = scanLineNum;
        this.debugLog(`Found disable marker at line ${scanLineNum}`);
        break;
      }
      if (!listItemRegex.test(lineContent)) {
        this.debugLog(
          `Scan hit non-list item line at ${scanLineNum}, stopping marker search.`
        );
        break;
      }
    }
    if (listMarkerFound !== null) {
      effectiveSortingEnabled = listMarkerFound;
      this.debugLog(
        `List marker found at line ${foundMarkerLine}. Effective sorting overridden to: ${effectiveSortingEnabled} (Source: ${settingSource})`
      );
    } else {
      this.debugLog(
        `No list marker found above line ${clickedLineNumber}. Effective sorting remains: ${effectiveSortingEnabled} (Source: ${settingSource})`
      );
    }
    if (!effectiveSortingEnabled) {
      this.debugLog(
        `Checkbox sorting disabled by ${settingSource} setting. Aborting sort logic.`
      );
      return;
    }
    this.debugLog(
      `sortCheckboxesAroundClick: Proceeding with sort for line: ${clickedLineNumber}`
    );
    try {
      const clickedLineText2 = editor.getLine(clickedLineNumber);
      const currentIndent2 = this.getIndentationLevel(clickedLineText2);
      const listItemRegex2 = /^\s*[-*+]\s+/;
      const tickedCheckboxRegex = /^\s*[-*+]\s+\[x\]/;
      const isCurrentlyTicked = tickedCheckboxRegex.test(clickedLineText2);
      const isNowTicked = !isCurrentlyTicked;
      if (!listItemRegex2.test(clickedLineText2)) {
        console.warn(
          `Line ${clickedLineNumber} is not a list item. Aborting action.`
        );
        return;
      }
      this.debugLog(
        `Click detected on line ${clickedLineNumber}. Current state: ${isCurrentlyTicked ? "Ticked" : "Unticked"}. New state: ${isNowTicked ? "Ticked" : "Unticked"}. Indent: ${currentIndent2}`
      );
      let blockStartLine2 = clickedLineNumber;
      for (let i2 = clickedLineNumber - 1; i2 >= 0; i2--) {
        const line = editor.getLine(i2);
        const indent = this.getIndentationLevel(line);
        if (!listItemRegex2.test(line)) break;
        if (indent === currentIndent2) {
          blockStartLine2 = i2;
        } else if (indent < currentIndent2) {
          break;
        }
      }
      let blockEndLine = clickedLineNumber;
      for (let i2 = clickedLineNumber + 1; i2 < totalLines; i2++) {
        const line = editor.getLine(i2);
        const indent = this.getIndentationLevel(line);
        if (!listItemRegex2.test(line)) break;
        if (indent === currentIndent2) {
          blockEndLine = i2;
        } else if (indent < currentIndent2) {
          break;
        }
      }
      this.debugLog(
        `Peer block boundaries (inclusive): ${blockStartLine2} to ${blockEndLine}`
      );
      const untickedItemsData = [];
      const tickedItemsData = [];
      let i = blockStartLine2;
      while (i <= blockEndLine) {
        const currentPeerLineText = editor.getLine(i);
        const currentPeerIndent = this.getIndentationLevel(currentPeerLineText);
        if (!listItemRegex2.test(currentPeerLineText) || currentPeerIndent !== currentIndent2) {
          i++;
          continue;
        }
        let peerTreeEndLine = i;
        for (let j = i + 1; j < totalLines; j++) {
          const descLineText = editor.getLine(j);
          const descIndent = this.getIndentationLevel(descLineText);
          if (!listItemRegex2.test(descLineText) || descIndent <= currentPeerIndent) {
            break;
          }
          peerTreeEndLine = j;
        }
        this.debugLog(
          `Peer at ${i}: Tree detected from line ${i} to ${peerTreeEndLine}`
        );
        let peerTreeText = "";
        for (let k = i; k <= peerTreeEndLine; k++) {
          peerTreeText += editor.getLine(k) + (k === totalLines - 1 ? "" : "\n");
        }
        let isPeerTickedForSorting;
        if (i === clickedLineNumber) {
          isPeerTickedForSorting = isNowTicked;
          const lines = peerTreeText.split("\n");
          if (lines.length > 0) {
            if (isNowTicked)
              lines[0] = lines[0].replace("[ ]", "[x]");
            else lines[0] = lines[0].replace("[x]", "[ ]");
            peerTreeText = lines.join("\n");
            this.debugLog(
              `Updated text for clicked item (lines ${i}-${peerTreeEndLine}) for new state: ${isNowTicked ? "Ticked" : "Unticked"}`
            );
          }
        } else {
          isPeerTickedForSorting = tickedCheckboxRegex.test(currentPeerLineText);
        }
        const itemData = { text: peerTreeText, originalLine: i };
        if (isPeerTickedForSorting) {
          tickedItemsData.push(itemData);
        } else {
          if (i == blockEndLine && !itemData.text.endsWith("\n") && tickedItemsData.length > 0 && !tickedItemsData[0].text.startsWith("\n")) {
            itemData.text += "\n";
          }
          untickedItemsData.push(itemData);
        }
        i = peerTreeEndLine + 1;
      }
      const finalBlockText = untickedItemsData.map((d) => d.text).join("") + tickedItemsData.map((d) => d.text).join("");
      let overallBlockEndLine = blockEndLine;
      for (let i2 = blockEndLine + 1; i2 < totalLines; ++i2) {
        const line = editor.getLine(i2);
        const indent = this.getIndentationLevel(line);
        if (!listItemRegex2.test(line) || indent < currentIndent2) break;
        overallBlockEndLine = i2;
      }
      this.debugLog(
        `Entire structure to replace spans ${blockStartLine2} to ${overallBlockEndLine}`
      );
      const deleteFrom = { line: blockStartLine2, ch: 0 };
      const deleteTo = overallBlockEndLine === totalLines - 1 ? {
        line: overallBlockEndLine,
        ch: editor.getLine(overallBlockEndLine).length
      } : { line: overallBlockEndLine + 1, ch: 0 };
      let textToInsert = finalBlockText;
      if (!textToInsert.endsWith("\n") && overallBlockEndLine < totalLines - 1) {
        textToInsert += "\n";
      }
      if (textToInsert.endsWith("\n") && overallBlockEndLine === totalLines - 1) {
        textToInsert = textToInsert.slice(0, -1);
      }
      const originalBlockText = editor.getRange(deleteFrom, deleteTo);
      if (textToInsert.trim() === originalBlockText.trim()) {
        this.debugLog("No changes needed.");
        return;
      }
      this.debugLog(
        `Replacing lines ${blockStartLine2}-${overallBlockEndLine} with new sorted block.`
      );
      editor.transaction({
        changes: [
          { from: deleteFrom, to: deleteTo, text: textToInsert }
        ]
      });
      this.debugLog(
        `Sorted checkbox block containing original line ${clickedLineNumber}.`
      );
    } catch (e) {
      console.error(
        `sortCheckboxesAroundClick: Error processing line ${clickedLineNumber}:`,
        e
      );
    }
  }
  // --- getIndentationLevel --- (remains the same)
  getIndentationLevel(line) {
    const match = line.match(/^\s*/);
    return match ? match[0].length : 0;
  }
  onunload() {
  }
};
var CheckboxSortSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enable checkbox sorting globally").setDesc(
      "If enabled, clicking checkboxes will sort them within their peer group (unticked first, then ticked). This can be overridden by file frontmatter or list markers later."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableGlobalCheckboxSort).onChange(async (value) => {
        this.plugin.debugLog(
          "Global sort setting changed:",
          value
        );
        this.plugin.settings.enableGlobalCheckboxSort = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable debug mode").setDesc("Show detailed debugging information in console").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.debugMode).onChange(async (value) => {
        this.plugin.settings.debugMode = value;
        await this.plugin.saveSettings();
      })
    );
  }
};


/* nosourcemap */